resolver: lts-14.0
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - wabt
  - wasm-toolkit
ghc-build: standard
setup-info:
  ghc:
    linux64:
      8.6.5:
        url: https://5566-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 4547f0dbb95ce23b486f04278d737024595b6e33328c1be9f04c8473c591c43e
    macosx:
      8.6.5:
        url: https://5563-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: 12a2f64b69e1f93a3d281f6f80cc8ff99b9827b49c1c444c6557a6886a4c6e94
