steps:

  - key: "pandoc"
    label: "pandoc"
    command: |
      docker pull terrorjack/asterius:latest
      docker run \
        --env UID=$(id --user) \
        --env GID=$(id --group) \
        --rm \
        --volume $(pwd):/workspace \
        --workdir /workspace/pandoc \
        terrorjack/asterius:latest \
        /workspace/build.sh
    artifact_paths:
      - "pandoc.tar"

  - key: "ormolu"
    label: "ormolu"
    command: |
      docker pull terrorjack/asterius:latest
      docker run \
        --env UID=$(id --user) \
        --env GID=$(id --group) \
        --rm \
        --volume $(pwd):/workspace \
        --workdir /workspace/ormolu \
        terrorjack/asterius:latest \
        /workspace/build.sh
    artifact_paths:
      - "ormolu.tar"
