steps:

  - key: "asterius-profile"
    label: "asterius-profile"
    command: |
      cd /tmp
      git clone --branch master --depth 1 https://github.com/tweag/asterius.git
      cd asterius

      docker pull debian:sid
      docker build \
        --build-arg UID=$(id --user) \
        --build-arg GID=$(id --group) \
        --build-arg jobs=8 \
        --compress \
        --file profile.Dockerfile \
        --network host \
        --no-cache \
        --tag asterius:profile \
        .
      docker run \
        --env UID=$(id --user) \
        --env GID=$(id --group) \
        --rm \
        --volume $(pwd):/asterius \
        --workdir /asterius \
        asterius:profile \
        .buildkite/profile.sh
      docker rmi asterius:profile
      buildkite-agent artifact upload "/tmp/asterius/.buildkite/reports/*"
