name: pipeline

on:
  - push
  - pull_request

jobs:

  boot:
    name: boot
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          cabal-version: 3.2.0.0
          stack-version: 2.3.3
          enable-stack: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.9.0

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-deps
        run: |
          .github/workflows/setup-deps.sh

      - name: boot
        run: |
          .github/workflows/boot.sh

      - name: upload-cache
        uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: |
            ~/.stack
            **/.stack-work

  build:
    name: build-${{ matrix.backend }}
    needs: boot
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        backend:
          - binaryen
          # - wasm-toolkit
    env:
      ASTERIUS_BACKEND: ${{ matrix.backend }}
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          cabal-version: 3.2.0.0
          stack-version: 2.3.3
          enable-stack: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.9.0

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-deps
        run: |
          .github/workflows/setup-deps.sh

      - name: download-cache
        uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: |
            ~/.stack
            **/.stack-work

      - name: setup-wasm-deps
        run: |
          . ./.envrc
          ahc-cabal v1-update
          pushd ghc-toolkit/boot-libs
          ahc-cabal v1-install -j2 \
            wai-middleware-caching
          popd

      - name: build
        run: |
          cd yhseq/
          ahc-cabal v1-build
          ahc-cabal install yhseq
          cd ../
          cd yhseq-web/
          ahc-cabal v1-build
          cd ../
